name: Python CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # The OS where the tests will run

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set Python version for the workflow

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies

    - name: Run tests
      run: |
        pytest  # Run the tests with pytest
